# Generated by Django 2.1.3 on 2018-11-04 07:59

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to=ocr.models.path_and_rename)),
                ('OCRData', models.TextField()),
            ],
        ),
    ]
